# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-tNPkoisPqZ3oQfzMosZK4y2IrtYRwp

Online Learning Platform Page Visit Analysis ● From: Minor 1 – EDA ● Extension: Analyze page visits → content popularity ● Add-ons: Bar plots, summary stats ● Difficulty: Easy
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "user_id": [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
    "page_name": [
        "Python Course", "Java Course", "Python Course", "ML Course", "Python Course",
        "Quiz 1", "Quiz 1", "Video Lecture", "Video Lecture", "Python Course"
    ],
    "content_type": [
        "Course", "Course", "Course", "Course", "Course",
        "Quiz", "Quiz", "Video", "Video", "Course"
    ],
    "visit_duration": [30, 25, 35, 40, 20, 15, 18, 45, 50, 28]
}

df = pd.DataFrame(data)

print(df)

print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

total_visits = len(df)
unique_users = df["user_id"].nunique()
average_duration = df["visit_duration"].mean()

print("\nSummary Statistics")
print("Total Visits:", total_visits)
print("Unique Users:", unique_users)
print("Average Visit Duration:", round(average_duration, 2))

page_visits = df["page_name"].value_counts()
print("\nPage Visit Count:")
print(page_visits)

content_popularity = df["content_type"].value_counts()
print("\nContent Type Popularity:")
print(content_popularity)

page_visits.plot(kind="bar")
plt.title("Page Visit Analysis")
plt.xlabel("Page Name")
plt.ylabel("Number of Visits")
plt.show()

content_popularity.plot(kind="bar")
plt.title("Content Type Popularity")
plt.xlabel("Content Type")
plt.ylabel("Number of Visits")
plt.show()

avg_duration = df.groupby("content_type")["visit_duration"].mean()
print("\nAverage Visit Duration by Content Type:")
print(avg_duration)

avg_duration.plot(kind="bar")
plt.title("Average Visit Duration by Content Type")
plt.xlabel("Content Type")
plt.ylabel("Duration (Minutes)")
plt.show()